XLSX.openxlsx("Data/ATP_Cost-Data-output-BI-$Batching_Interval-scenario-$scenario-forecast.xlsx", mode="rw") do xf
    sheet = XLSX.addsheet!(xf,"Final Decisions Forecast") 
    column=1
    row=1
    sheet[row,column] = "Order ID."
    column+=1
    sheet[row,column] = "Product type"
    column+=1
    sheet[row,column] = "Earliest due time"
    column+=1
    sheet[row,column] = "Latest due time"
    column+=1
    sheet[row,column] = "Netted quantites"
    column+=1
    sheet[row,column] = "Quantites"
    column+=1
    sheet[row,column] = "Rejection Penalty"
    column+=1
    sheet[row,column] = "Acceptance/declination"
    column+=1
    sheet[row,column] = "Missed"
    column+=1
    sheet[row,column] = "Promised quanitites"
    column+=1
    sheet[row,column] = "partial Penalty"
    column+=1
    sheet[row,column] = "denial Penalty"
    column+=1
    sheet[row,column] = "total Penalty"
    for k in eachindex(FQ_ID)
           row+=1
           column=1
           sheet[row,column] = FQ_ID[k]
           column+=1
           sheet[row,column] = FQ_P[k]
           column+=1
           sheet[row,column] = FQ_DE[k]
           column+=1
           sheet[row,column] = FQ_DL[k]
           column+=1
           sheet[row,column] = FQ[k]
           column+=1
           sheet[row,column] = FQ_qty[k]
           column+=1
           sheet[row,column] = πS[FQ_P[k]]*0.25
           column+=1
           sheet[row,column] = FQ_order_decision[k]
           column+=1
           sheet[row,column] = FQ_order_missed[k]
           column+=1
           sheet[row,column] = FQ_Order_promised_quantites[k]
           column+=1
           sheet[row,column] = -πS[FQ_P[k]]*0.25*0.25*(FQ[k]*FQ_order_decision[k]-FQ_Order_promised_quantites[k])
           column+=1
           sheet[row,column] = -πS[FQ_P[k]]*0.25*FQ[k]*(1-FQ_order_decision[k])
           column+=1
           sheet[row,column] = -πS[FQ_P[k]]*0.25*FQ[k]*(1-FQ_order_decision[k])-πS[FQ_P[k]]*0.25*0.25*(FQ[k]*FQ_order_decision[k]-FQ_Order_promised_quantites[k])
           column+=1
    end
end
