XLSX.openxlsx("Data/ATP_Cost-Data-output-BI-$Batching_Interval-scenario-$scenario-forecast.xlsx", mode="rw") do xf
     sheet = XLSX.addsheet!(xf,"Final Decisions Orders") 
     column=1
     row=1
     sheet[row,column] = "Order ID."
     column+=1
     sheet[row,column] = "Product type"
     column+=1
     sheet[row,column] = "Arrival Time"
     column+=1
     sheet[row,column] = "Response Time"
     column+=1
     sheet[row,column] = "Earliest due time"
     column+=1
     sheet[row,column] = "Latest due time"
     column+=1
     sheet[row,column] = "Minimum quantites"
     column+=1
     sheet[row,column] = "Maximum quantities"
     column+=1
     sheet[row,column] = "Selling price"
     column+=1
     sheet[row,column] = "Priority"
     column+=1
     sheet[row,column] = "Rejection Penalty"
     column+=1
     sheet[row,column] = "Acceptance/declination"
     column+=1
     sheet[row,column] = "Promised due date"
     column+=1
     sheet[row,column] = "Promised quantities"
     column+=1
     sheet[row,column] = "Partial filled"
     column+=1
     sheet[row,column] = "Rescheduled"
     column+=1
     sheet[row,column] = "Missed"
     column+=1
     sheet[row,column] = "Promised quanitites"
     column+=1
     sheet[row,column] = "Parital rejction Penalty"
     column+=1
     sheet[row,column] = "denial Penalty"
     column+=1
     sheet[row,column] = "Total Penalty"
     for k in eachindex(order_Id)
            row+=1
            column=1
            sheet[row,column] = order_Id[k]
            column+=1
            sheet[row,column] = Product_Type[k]
            column+=1
            sheet[row,column] = Arrival_Time[k]
            column+=1
            sheet[row,column] = Response_Time[k]
            column+=1
            sheet[row,column] = Earliest_Due_Time[k]
            column+=1
            sheet[row,column] = Latest_Due_Time[k]
            column+=1
            sheet[row,column] = Min_Order_Quantity[k]
            column+=1
            sheet[row,column] = Max_Order_Quantity[k]
            column+=1
            sheet[row,column] = πS[Product_Type[k]]
            column+=1
            sheet[row,column] = Order_priority[k]
            column+=1
            sheet[row,column] = πS[Product_Type[k]]*Order_priority[k]
            column+=1
            sheet[row,column] = order_decision[k]
            column+=1
            sheet[row,column] = order_assigned_due_time[k]
            column+=1
            sheet[row,column] = Order_promised_quantites[k]
            column+=1
            sheet[row,column] = (abs(Max_Order_Quantity[k] - Order_promised_quantites[k]) > 0.01 ? 1 : 0 )*order_decision[k]
            column+=1
            sheet[row,column] = Order_Reschedule[k]
            column+=1
            sheet[row,column] = order_missed[k]
            column+=1
            sheet[row,column] = Order_promised_quantites[k]
            column+=1
            sheet[row,column] =  πS[Product_Type[k]]*Order_priority[k]*0.75*(Max_Order_Quantity[k]*order_decision[k]-Order_promised_quantites[k]) 
            column+=1
            sheet[row,column] = πS[Product_Type[k]]*Order_priority[k]*Min_Order_Quantity[k]*(1-order_decision[k])
            column+=1
            sheet[row,column] = πS[Product_Type[k]]*Order_priority[k]*Min_Order_Quantity[k]*(1-order_decision[k]) + πS[Product_Type[k]]*Order_priority[k]*(Max_Order_Quantity[k]*order_decision[k]-Order_promised_quantites[k]) 
            column+=1
     end
 end
 